# Generated by Django 5.0 on 2024-03-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='college',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='major',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='year_in_school',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
