# Generated by Django 4.2.9 on 2024-03-15 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseapp', '0002_person_age_person_college_person_gender_person_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletimeslot',
            name='person',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='availblity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='organizer',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to=settings.AUTH_USER_MODEL),
        ),
    ]
