# Generated by Django 5.0 on 2024-03-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_person_age_person_college_person_gender_person_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='year_in_school',
            field=models.CharField(blank=True, null=True),
        ),
    ]
