# Generated by Django 5.0 on 2024-01-22 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_dayofweek_permissionlevel_resourcecategory_timeslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='permissionLevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.permissionlevel'),
        ),
        migrations.AddField(
            model_name='person',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.university'),
        ),
    ]
