# Generated by Django 4.2.9 on 2024-03-15 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_alter_person_year_in_school'),
        ('baseapp', '0003_update_calendar_event'),
    ]

    operations = [
    ]
