# Generated by Django 5.0 on 2024-02-15 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_person_permissionlevel_person_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueLeaveReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveReason', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='studentqueue',
            name='notes',
            field=models.CharField(blank=True, max_length=1048, null=True),
        ),
        migrations.AddField(
            model_name='studentqueue',
            name='leaveReason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.queueleavereason'),
        ),
    ]
