# Generated by Django 5.0 on 2024-02-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_queueleavereason_studentqueue_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='permissionLevel',
        ),
    ]
