# Generated by Django 5.0 on 2024-02-27 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_remove_person_permissionlevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availabletimeslot',
            old_name='dayOfWeek',
            new_name='dayOfWeekId',
        ),
        migrations.RenameField(
            model_name='availabletimeslot',
            old_name='person',
            new_name='personId',
        ),
        migrations.RenameField(
            model_name='availabletimeslot',
            old_name='timeSlot',
            new_name='timeSlotId',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='university',
            new_name='universityId',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='zip',
            new_name='zipCode',
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='image',
            field=models.CharField(default='https://picsum.photos/id/147/2000/1700', max_length=255),
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('eventLocation', models.CharField(max_length=255)),
                ('backgroundColor', models.CharField(max_length=255)),
                ('allDay', models.BooleanField()),
                ('editable', models.BooleanField()),
                ('oneDayEvent', models.BooleanField()),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('organizerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='eventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.calendarevent')),
                ('personId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.person')),
            ],
        ),
        migrations.RenameModel(
            old_name='Resource',
            new_name='ResourceDetail',
        ),
        migrations.CreateModel(
            name='FavoriteResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField()),
                ('personId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.person')),
                ('resourceId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.resourcedetail')),
            ],
        ),
    ]
