# Generated by Django 5.0 on 2024-03-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_update_calendar_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='contact_preference',
            field=models.CharField(blank=True, default='TEXT', null=True),
        ),
    ]
