# Generated by Django 5.0 on 2024-02-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_rename_dayofweek_availabletimeslot_dayofweekid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availabletimeslot',
            old_name='notes',
            new_name='dayOfWeek',
        ),
        migrations.RenameField(
            model_name='availabletimeslot',
            old_name='personId',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='availabletimeslot',
            old_name='timeSlotId',
            new_name='timeSlot',
        ),
        migrations.RenameField(
            model_name='calendarevent',
            old_name='organizerId',
            new_name='organizer',
        ),
        migrations.RenameField(
            model_name='eventattendee',
            old_name='eventId',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='eventattendee',
            old_name='personId',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='favoriteresource',
            old_name='personId',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='favoriteresource',
            old_name='resourceId',
            new_name='resourceDetail',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='universityId',
            new_name='university',
        ),
        migrations.RemoveField(
            model_name='availabletimeslot',
            name='dayOfWeekId',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='dayOfWeek',
            field=models.CharField(max_length=255, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='image',
            field=models.CharField(default='https://picsum.photos/id/147/2000/1700', max_length=500),
        ),
        migrations.AlterField(
            model_name='resourcedetail',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resourcedetail',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
