# Generated by Django 5.0 on 2024-03-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_rename_notes_availabletimeslot_dayofweek_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PermissionLevel',
        ),
    ]
