# Generated by Django 5.0 on 2024-02-29 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_rename_notes_availabletimeslot_dayofweek_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.person')),
                ('resourceDetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.resourcedetail')),
            ],
        ),
        migrations.AddField(
            model_name='resourcedetail',
            name='favorited_by',
            field=models.ManyToManyField(through='baseapp.FavoriteResources', to='baseapp.person'),
        ),
    ]
