# Generated by Django 5.0 on 2024-03-04 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_delete_permissionlevel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='studentqueue',
        #     name='id',
        # ),
        migrations.AddField(
            model_name='person',
            name='events',
            field=models.ManyToManyField(to='baseapp.calendarevent'),
        ),
        migrations.AlterField(
            model_name='studentqueue',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_queue', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='eventAttendee',
        ),
    ]
