# Generated by Django 5.0 on 2024-03-01 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_favoriteresources_resourcedetail_favorited_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteresources',
            name='person',
        ),
        migrations.RemoveField(
            model_name='favoriteresources',
            name='resourceDetail',
        ),
        migrations.RemoveField(
            model_name='resourcedetail',
            name='favorited_by',
        ),
        migrations.AddField(
            model_name='resourcedetail',
            name='favoritedBy',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FavoriteResources',
        ),
    ]
