# Generated by Django 5.0 on 2024-03-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_delete_permissionlevel'),
        ('baseapp', '0009_remove_favoriteresources_person_and_more'),
    ]

    operations = [
    ]
