# Generated by Django 5.0 on 2024-03-06 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0011_remove_resourcedetail_image_remove_studentqueue_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcedetail',
            name='favoritedBy',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        )
    ]
