# Generated by Django 4.2.9 on 2024-03-09 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0011_alter_studentqueue_id_alter_studentqueue_person'),
        ('baseapp', '0012_remove_studentqueue_id_and_more'),
    ]

    operations = [
    ]
