# Generated by Django 5.0 on 2024-03-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0013_merge_20240309_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='timeSlots',
        ),
        migrations.AddField(
            model_name='studentqueue',
            name='queueTime',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FavoriteResource',
        ),
    ]
