# Generated by Django 4.2.9 on 2024-03-09 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseapp', '0013_merge_20240308_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='person',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='person',
            name='timeSlots',
        ),
        migrations.AlterField(
            model_name='availabletimeslot',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_time_slot', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resourcedetail',
            name='favoritedBy',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
