# docker-compose.yml
version: '3'
services:
  # SERVER
  django-server-backend:
    container_name: django-server-backend
    restart: always
    env_file:
      - ./django_server/.env.dev
    build:
      context: ./django_server # declaring the current (root) dir as the context so we can access "Pipfile"
      dockerfile: Dockerfile
    depends_on:
      - nextjs-server-backend
    ports:
      - "8000:8000"
    links:
      - nextjs-server-backend
    entrypoint: /django_server/entrypoint.sh


  # CLIENT
  nextjs-server-backend:
    container_name: nextjs-server-backend
    build:
      context: ./nextjs_server  
      dockerfile: Dockerfile
    env_file: # setting env file for local development
      - ./nextjs_server/.env.local
    depends_on:
      - db-backend
    ports:
      - "3000:3000"
    links:
      - db-backend
    entrypoint: /app/server/entrypoint.sh


  # DATABASE
  db-backend:
    container_name: db-backend
    restart: always
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - "5432:5432"


  # NGINX SERVER
  # nginx-backend:
  #   container_name: nginx-backend
  #   build:
  #     context: ./nginx/development
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   links:
  #     - nextjs-server-backend
  #     - django-server-backend
