import { SessionProvider } from "next-auth/react"
import { AppRouterCacheProvider } from '@mui/material-nextjs/build/v14-appRouter';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout(props) {
 return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <SessionProvider session={props.session}>
          {props.children}
          </SessionProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
